version: "3.7"
services:
  api:
    build: .
    container_name: chrono_bastion-api
    ports:
      - "${APP_PORT:-10000}:10000"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      ENABLE_RELOAD_UVICORN: ${ENABLE_RELOAD_UVICORN}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      ROOT_PATH: ""
    volumes:
      - ".:/srv"
    networks:
      - internal
    hostname: chrono_bastion
networks:
  internal:
    external: false
